### ISSUE TITLE
Tags view

### ISSUE THREAD

**Issue by yungpanda** [oSoc15/biblo-server#4]
I like the idea with the tags, but it's not very clear yet. What I would do is:
- Order alphabetically (you can easily do this in Laravel in the query ->orderBy('table_name') )
- Make sure all labels/tag text starts at the same pixels of the left side, and make sure the X is same pixels from right side everywhere (so basically split X and Text)

**Comment by wesobi** [comment]
Alphabetical ordering is done. 

In TagsController, instead of requesting All the tags, I now display all the names in ascending order from the DB-table tags

**Comment by wesobi** [comment]
Saved another panda, huzzah!
